name: 'tsurugi-annotations-action'
description: 'Generate check-run annotations from outputs of static analysis tools'
author: 'project-tsurugi'
inputs:
  github_token:
    description: Use this if you wish to use a different GitHub token than the one provided by the workflow.
    required: true
    default: ${{ github.token }}
  strict:
    description: If annotation exists, set action to fail.
    required: true
    default: true
  clang_tidy_input:
    description: 'input file of generating Clang-Tidy annotation'
    required: true
    default: 'build/clang-tidy.log'
  ctest_input:
    description: 'input file of generating CTest annotation'
    required: true
    default: 'build/**/*_gtest_result.xml'
  doxygen_input:
    description: 'input file of generating Doxygen annotation'
    required: true
    default: 'build/doxygen-error.log'
  junit_input:
    description: 'input file of generating JUnit annotation'
    required: true
    default: 'build/test-results/**/TEST-*.xml'
  spotbugs_input:
    description: 'input file of generating SpotBugs annotation'
    required: true
    default: 'build/reports/spotbugs/main/*.xml'
  checkstyle_input:
    description: 'input file of generating Checkstyle annotation'
    required: true
    default: 'build/reports/checkstyle/main.xml'
  junit_test_src_dir:
    description: 'test source root directory'
    required: true
    default: 'src/test/java'
  matrix:
    description: 'matrix context'
    required: false
  checker:
    description: 'enabled checker list (comma separated string)'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
