name: CI
on: [pull_request, push]

jobs:
  build:
    runs-on: [self-hosted, docker]
    container: node:14

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: npm install
      - run: npm run build
      - run: npm run lint
      - run: npm run pack
      - run: npm test
