name: tsurugi-annotations-action-CI

on: [pull_request, push, workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash

    steps:
      - name: Setup_Node
        uses: actions/setup-node@v4
        with:
         node-version: 16

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Lint
        run: |
          npm run lint

      - name: Test
        run: |
          npm test
